### ISSUE TITLE
How to figure out locationId and categoryId from search url?

### ISSUE THREAD

**Issue by phddb** [LegendaryFire/kijiji-scraper#1]
Hi there, 

Is this repo out-of-date?   It claims that I can find a `locationId` and `categoryId` in the URL of my search. Just now using the site gave me the following URL (searching for toasters in Montreal):

`https://www.kijiji.ca/b-ville-de-montreal/toaster/k0l1700281?dc=true&sort=dateDesc`

What are my location and category ids?

**Comment by LegendaryFire** [comment]
Hey there,

The repo should be working just fine. The `categoryId` and `locationId` are just hidden in there. For the particular URL you've provided the `categoryId` would be `0` and the `locationId` would be `1700281`.

If you have any other questions feel free to reach out.
